### ISSUE TITLE
Activesupport 7 breaks bundling

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/cocina-models#278]
```
$ bundle exec rspec

An error occurred while loading spec_helper.
Failure/Error: require 'active_support/core_ext/string'

NameError:
  uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState
# ./lib/cocina/models.rb:12:in `<top (required)>'
# ./spec/spec_helper.rb:4:in `require'
# ./spec/spec_helper.rb:4:in `<top (required)>'
```

**Comment by jcoyne** [comment]
Fixed by #279
